version: '3.8'

services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5001
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty12345
      - POSTGRES_DB=reviews_db
      - PYTHONIOENCODING=UTF-8
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
      - ENABLE_PARSER=false  # Переключатель парсера
      - TITLE=кафе  # Значение по умолчанию
      - BASE_URL=https://yandex.ru/maps/213/moscow/search/кафе  # Значение по умолчанию
    shm_size: 20gb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - default

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty12345
      - POSTGRES_DB=reviews_db
      - POSTGRES_INITDB_ARGS=--encoding=UTF8
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5001:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

volumes:
  pgdata:

networks:
  default:
    driver: bridge